<?php
/**
* Monitoria: Estrutura de Dados
* Para adicionar aula: copie um bloco e troque o youtube_id pelo ID do vídeo.
 */

return[
        'id'        => 'estrutura-de-dados-1',
        'id_json'   => 'ed1',
        'titulo'    => 'Vídeo Aula de Estrutura de Dados 1',
        'subtitulo' => 'Monitoria de Estrutura de Dados 1',
        'descricao' => 'Nas vídeo aulas de Estrutura de Dados 1 você pode assistir gravações de monitorias anteriores, cobrindo estruturas fundamentais como listas encadeadas, pilhas, filas, árvores e grafos. A monitoria aborda implementação prática em C e análise de complexidade de algoritmos.',
        'cor'       => '#0f9d58',
        'icone'     => '🌲',
        'semestres' => ['2025.2', '2025.1', '2024.2', '2024.1', '2023.2'],
        'aulas'     => [
            [
                'titulo'     => 'Monitoria 01 - Introdução e Revisão de Ponteiros',
                'data'       => '08 de Outubro, 2025',
                'duracao'    => '1h 23 min',
                'modulo'     => 'Módulo 1',
                'semestre'   => '2025.2',
                'youtube_id' => 'SUBSTITUA_PELO_ID_DO_YOUTUBE',
            ],
            [
                'titulo'     => 'Monitoria 02 - Listas Encadeadas',
                'data'       => '15 de Outubro, 2025',
                'duracao'    => '2h 05 min',
                'modulo'     => 'Módulo 1',
                'semestre'   => '2025.2',
                'youtube_id' => 'SUBSTITUA_PELO_ID_DO_YOUTUBE',
            ],
            [
                'titulo'     => 'Monitoria 03 - Pilhas e Filas',
                'data'       => '22 de Outubro, 2025',
                'duracao'    => '1h 40 min',
                'modulo'     => 'Módulo 2',
                'semestre'   => '2025.2',
                'youtube_id' => 'SUBSTITUA_PELO_ID_DO_YOUTUBE',
            ],
            [
                'titulo'     => 'Aula 01-Vetores, matrizes e pilhas',
                'data'       => '27 de Fevereiro, 2023',
                'duracao'    => '1h 34 min',
                'modulo'     => 'Módulo 1',
                'semestre'   => '2023.2',
                'youtube_id' => 'hUOK8LcYwxw',
            ],
            [
                'titulo'     => 'Aula 02 - Pilhas e filas',
                'data'       => '27 de Fevereiro, 2023',
                'duracao'    => '1h 57 min',
                'modulo'     => 'Módulo 1',
                'semestre'   => '2023.2',
                'youtube_id' => 'h1V6zZUaccg',
            ],
            [
                'titulo'     => 'Aula 03 - Resolução de Provas Anteriores',
                'data'       => '27 de Fevereiro, 2023',
                'duracao'    => '1h 48 min',
                'modulo'     => 'Módulo 1',
                'semestre'   => '2023.2',
                'youtube_id' => 'aSypgagn7So',
            ],
            [
                'titulo'     => 'Aula 04 - Resolução da Prova 1 de 2023',
                'data'       => '27 de Fevereiro, 2023',
                'duracao'    => '1h 27 min',
                'modulo'     => 'Módulo 1',
                'semestre'   => '2023.2',
                'youtube_id' => '3syKjzG_RMA',
            ],
            [
                'titulo'     => 'Aula 05 - Listas Encadeadas',
                'data'       => '27 de Fevereiro, 2023',
                'duracao'    => '1h 11 min',
                'modulo'     => 'Módulo 2',
                'semestre'   => '2023.2',
                'youtube_id' => '4kPO1zG983s',
            ],
            [
                'titulo'     => 'Aula 06 - Listas Encadeadas',
                'data'       => '27 de Fevereiro, 2023',
                'duracao'    => '21 min',
                'modulo'     => 'Módulo 2',
                'semestre'   => '2023.2',
                'youtube_id' => '8F7ERIM7dXQ',
            ],
            [
                'titulo'     => 'Aula 07 - Resolução de Provas Anteriores',
                'data'       => '27 de Fevereiro, 2023',
                'duracao'    => '1h 19 min',
                'modulo'     => 'Módulo 2',
                'semestre'   => '2023.2',
                'youtube_id' => 'x6eILl6xxI4',
            ],
            [
                'titulo'     => 'Aula 08 - Resolução de Questões',
                'data'       => '27 de Fevereiro, 2023',
                'duracao'    => '1h 18 min',
                'modulo'     => 'Módulo 2',
                'semestre'   => '2023.2',
                'youtube_id' => 'FJKoXvIuBrY',
            ],
            [
                'titulo'     => 'Aula 09 - Resolução de Questões',
                'data'       => '27 de Fevereiro, 2023',
                'duracao'    => '1h 14 min',
                'modulo'     => 'Módulo 2',
                'semestre'   => '2023.2',
                'youtube_id' => 'gSfjyvaed-Y',
            ],
            [
                'titulo'     => 'Aula 01 - Introdução',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '11 min',
                'modulo'     => 'Módulo 1',
                'semestre'   => '2024.1',
                'youtube_id' => 'nHWMDTzcqgo',
            ],
            [
                'titulo'     => 'Aula 02 - Vetores e Matrizes',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '7 min',
                'modulo'     => 'Módulo 1',
                'semestre'   => '2024.1',
                'youtube_id' => 'lKhcICyY_f4',
            ],
            [
                'titulo'     => 'Aula 03 - Tipos Abstratos de Dados',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '20 min',
                'modulo'     => 'Módulo 1',
                'semestre'   => '2024.1',
                'youtube_id' => '0qfDEde4SZE',
            ],
            [
                'titulo'     => 'Aula 04 - Pilha',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '39 min',
                'modulo'     => 'Módulo 1',
                'semestre'   => '2024.1',
                'youtube_id' => 'cyPXt8k1P3k',
            ],
            [
                'titulo'     => 'Aula 05 - Filas',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '1h 29 min',
                'modulo'     => 'Módulo 1',
                'semestre'   => '2024.1',
                'youtube_id' => '8pSN02Q-1CI',
            ],
            [
                'titulo'     => 'Aula 06 - Listas Simplesmente Encadeada (1/3)',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '40 min',
                'modulo'     => 'Módulo 2',
                'semestre'   => '2024.1',
                'youtube_id' => 'Pqrw_OlgGBk',
            ],
            [
                'titulo'     => 'Aula 07 - Listas Simplesmente Encadeada (2/3)',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '37 min',
                'modulo'     => 'Módulo 2',
                'semestre'   => '2024.1',
                'youtube_id' => 'bd7gsHQgT1c',
            ],
            [
                'titulo'     => 'Aula 08 - Listas Simplesmente Encadeada (3/3)',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '1h 00min',
                'modulo'     => 'Módulo 2',
                'semestre'   => '2024.1',
                'youtube_id' => 'MaKKYoDYLok',
            ],
            [
                'titulo'     => 'Aula 09 - Listas Duplamente Encadeadas',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '1h 05min',
                'modulo'     => 'Módulo 2',
                'semestre'   => '2024.1',
                'youtube_id' => 'PgJncF_-_Vg',
            ],
            [
                'titulo'     => 'Aula 10 - Listas Circulares',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '1h 52min',
                'modulo'     => 'Módulo 2',
                'semestre'   => '2024.1',
                'youtube_id' => 'T4RtOxAaBkE',
            ],
            [
                'titulo'     => 'Aula 11 - Árvores (1/3)',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '1h 33min',
                'modulo'     => 'Módulo 3',
                'semestre'   => '2024.1',
                'youtube_id' => 'A8mb_sADb54',
            ],
            [
                'titulo'     => 'Aula 12 - Árvores (2/3)',
                'data'       => '28 de Abril, 2024',
                'duracao'    => '1h 15min',
                'modulo'     => 'Módulo 3',
                'semestre'   => '2024.1',
                'youtube_id' => 'cz8ZKqKPgGE',
            ],
            [
            'titulo'     => 'Aula 13 - Árvores (3/3)',
            'data'       => '28 de Abril, 2024',
            'duracao'    => '1h 00min',
            'modulo'     => 'Módulo 3',
            'semestre'   => '2024.1',       
            'youtube_id' => 'KE2bAPNDEZc',
            ],
            [
            'titulo'     => 'Aula 13 - Árvores (3/3)',
            'data'       => '28 de Abril, 2024',
            'duracao'    => '1h 00min',
            'modulo'     => 'Módulo 1',
            'semestre'   => '2024.1',       
            'youtube_id' => 'KE2bAPNDEZc',
            ],
    ],
];